# Licensed to the Apache Software Foundation (ASF) under one or more contributor
# license agreements; and to You under the Apache License, Version 2.0.

# https://docs.travis-ci.com/user/languages/python/
language: python

install:
  - ./tools/travis/setupscan.sh

script:
  - ./tools/travis/scancode.sh
